version: "3"
volumes:
  gradle:
services:
  db:
    build: docker/db
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: paper_db
    volumes:
      ## 永続化 ##
       - "./docker/db/data:/var/lib/mysql"
       - "./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf"
       - "./log/mysql:/var/log/mysql"
    env_file: .env
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_USER: ${DB_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: research_paper_db
      TZ: ${TZ}
    expose:
      - "33036"
    ports:
      - "33036:3306"

  api:
    image: openjdk:11-jdk-slim-sid
    # command: bash -c "./gradlew build --continuous & ./gradlew bootRUN"
    command: java -jar build/libs/backend.jar
    container_name: paper_search_api
    working_dir: /app
    volumes:
      - ./backend/:/app
      - ./backend/gradle/:/root/.gradle
    env_file: .env
    environment:
      DB_USER: ${DB_ROOT_USER}
      DB_PASSWORD: ${DB_ROOT_PASSWORD}
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - db
