spring:
  datasource:
    url: jdbc:mysql://db:3306/research_paper_db?characteerEncoding=utf8&useSSL=false
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
    dbcp2:
      test-on-borrow: true
      test-while-idle: true
      validation-query: select sysdate()
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
