spring:
  datasource:
    url: jdbc:mysql://db:3306/research_paper_db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
    dbcp2:
      test-on-borrow: true
      test-while-idle: true
      validation-query: select sysdate()
