name: Frontend CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

defaults:
  run:
    working-directory: ./frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: npm install
        run: npm ci
      - name: run eslint
        run: npm run lint
      - name: run unit test
        run: npm test -- --coverage
      - name: codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./frontend/coverage/lcov.info
          fail_ci_if_error: true
          verbose: true
