name: Java CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

defaults:
  run:
    working-directory: ./backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: build with gradle
        run: ./gradlew build
      - name: codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./backend/build/reports/jacoco/test/jacocoTestReport.xml
          fail_ci_if_error: true
          verbose: true